services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      bash -c "
        export PYTHONPATH=/app &&
        cd /app &&
        pip install openpyxl --no-cache-dir &&
        pytest tests/ -v"